version: '3.8'

services:
  express-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: express
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password!
    ports:
      - "5436:5432"
    volumes:
      - pg-expressdata:/var/lib/postgresql/data
  
  dotnet-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: dotnet
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password!
    ports:
      - "5435:5432"
    volumes:
      - pg-dotnetdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

  express-app:
    build:
      context: .
      dockerfile: ./express/Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - express-db
    volumes:
      - .:/usr/src/app

volumes:
  pg-expressdata:
  pg-dotnetdata: